version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:14
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  adonis_app:
    container_name: adonis_app
    restart: always
    env_file:
      - .env
    build:
      context: .
      target: dependencies
    ports:
      - 3333:3333
    volumes:
      - ./:/home/node/app
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"

volumes:
  postgres_volume:


networks:
  default:
    name: hypolia_network
    external: true