version: '3.8'
name: leadcode

networks:
  leadcode:
    driver: bridge
    name: leadcode

services:
  postgres:
    container_name: postgres
    image: postgres:13
    networks:
      - leadcode
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend
    ports:
      - 5432:5432
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - leadcode
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootpassword
    command: server --console-address ":9001" /data
  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=password
    ports:
      - '6379:6379'
    volumes:
      - redis_volume:/var/lib/redis/data
    networks:
      - leadcode
  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: "postgres"  # Remplacez par l'adresse IP ou le nom du serveur de votre instance PostgreSQL
      DB_PORT: "5432"  # Port par défaut de PostgreSQL
      DB_DATABASE: "keycloak"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    command:
      - start-dev
    volumes:
      - keycloak_data:/path/to/keycloak/data


volumes:
  postgres_volume:
  redis_volume:
  minio_storage: {}
  keycloak_data: {}
