name: CI

on:
  workflow_call:
    secrets:
      CONTAINER_REGISTRY_TOKEN:
        required: true
      CONTAINER_REGISTRY_USERNAME:
        required: true
      CONTAINER_REGISTRY_ENDPOINT:
        required: true
      PAT:
        required: true
  workflow_dispatch:
    repository:
      required: true
      type: string
      description: "The repository to checkout"
    image-name:
      required: true
      type: string
      description: "The image name to build"
      default: "ruby"
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          repository: leadc0de/adonis-backend
          token: ${{ secrets.PAT }}
          fetch-tags: true
          fetch-depth: 0


      - name: Determine version
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Add Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/hypolia/${{ inputs.image-name }}
          tags: |
            latest
            buildcache
            ${{ steps.version.outputs.VERSION }}

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=hypolia/ruby:buildcache
          cache-to: type=gha,mode=max,scope=hypolia/ruby:buildcache

